### ISSUE TITLE
AR can be transitioned to verified while all AS's remain to be verified

### ISSUE THREAD

**Issue by andersonsmith** [bikalims/bika.lims#1977]
## Steps to reproduce

1. AR with AS's all in `to be verified` state.
2. From AR list view, select AR and use the verify button on list
3. AR transitions to `verified` while the AS's remain `to be verified`

## Current behavior

AR transitions to `verified` while the AS's remain `to be verified`

## Expected behavior

All AS's within the AR should also transition to the `verified` state.

## Screenshot (optional)

![pre_verify](https://cloud.githubusercontent.com/assets/15053675/24272091/f23be0f2-0fd8-11e7-8ab1-da6dacb24cc3.jpg)

![post_verification](https://cloud.githubusercontent.com/assets/15053675/24272096/f660c418-0fd8-11e7-822e-daf83ed032bc.jpg)

**Comment by andersonsmith** [comment]
Updated with screenshots showing the mismatch.

**Comment by ramonski** [comment]
Issue still there, I'm taking over this one.
