### ISSUE TITLE
Traceback for AR when an Analysis is used w/o 'Exponential format precision' set

### ISSUE THREAD

**Issue by ramonski** [bikalims/bika.lims#2004]
## Steps to reproduce

1. Create an Analysis Service and empty the field 'Exponential format precision' in 'Analysis'
2. Create a new AR and select this Service
3. Receive the Sample and add a Result, e.g. 15
4. The following Traceback is displayed:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.view, line 93, in __call__
  Module bika.lims.browser.bika_listing, line 1058, in contents_table
  Module bika.lims.browser.bika_listing, line 1237, in __init__
  Module bika.lims.browser.analyses, line 621, in folderitems
  Module bika.lims.content.analysis, line 992, in getFormattedResult
  Module bika.lims.utils.analysis, line 300, in format_numeric_result
  Module bika.lims.utils.analysis, line 91, in _format_decimal_or_sci
TypeError: bad operand type for abs(): 'NoneType'
```

## Current behavior

An empty 'Exponential format precision' value in Analysis Services lead to failing ARs

## Expected behavior

Graceful fallback handling for empty 'Exponential format precision' values

## Screenshot (optional)

<img width="1063" alt="brechungsindex_" src="https://cloud.githubusercontent.com/assets/713193/24471196/a4353e88-14c1-11e7-9a66-05d83e96f0c7.png">

bika.lims.content.analysisservice:
<img width="833" alt="screenshot_29_03_17__20_55" src="https://cloud.githubusercontent.com/assets/713193/24471343/20a97b0a-14c2-11e7-9fd4-868d09cb4b95.png">

**Comment by ramonski** [comment]
Does allwoing `None` values for `Precision` and `ExponentialPrecision` make sense at all?

**Comment by xispa** [comment]
I think that allowing `None` values for, at least `Precision` does not make sense atm. This could eventually change in future if you want to allow non-numeric results in Analysis (but in any case, such a change would probably mean a new object, other than the current AnalysisService).
