### ISSUE TITLE
Research: Can i18ndude pick up translations strings of JavaScript as well?

### ISSUE THREAD

**Issue by ramonski** [bikalims/bika.lims#2091]
## Description

Bika LIMS uses `jarn.jsi18n` to translate strings in JavaScript. Unfortunately these message strings need to get manually included into the `bika-manual.pot`, which is often forgotten.

The solution would be to make `i18ndude` do the work. But how to tell `i18ndude` to pick up `.js`

## Useful Links

- https://pypi.python.org/pypi/jarn.jsi18n
- https://pypi.python.org/pypi/i18ndude

**Comment by ramonski** [comment]
## For better understanding

`jarn.jsi18n` loads the `.po` files and store them into the browsers' localStorage with this command: 

```javascript
jarn.i18n.loadCatalog('bika');
_ = jarn.i18n.MessageFactory('bika', 'de');
_('Analysis');
"Analyse"
```

Please install the `FireStorage` extension for FF to see the `localStorage` and flush it if the translations changed:

<img width="786" alt="lims__standort_hagen_" src="https://user-images.githubusercontent.com/713193/27040902-ae185988-4f92-11e7-8ff9-dbe805376bef.png">

**Comment by xispa** [comment]
@ramonski , some work on this regard here: https://github.com/naralabs/bika.lims/pull/226

**Comment by ramonski** [comment]
Thanks @xispa for pointing this out.
I solved this requirement in the end with Handlebars in the new AR Add view:
https://github.com/bikalims/bika.lims/blob/master/bika/lims/browser/analysisrequest/templates/ar_add2.pt#L28
IMO we should think about dropping `jarn.jsi18n` completely, because JS shouldn't deliver translated content at all.

**Comment by xispa** [comment]
Cool, thanks. I'll give a try in lists!. Although we are now using brains to render them, we noticed the rendering was very slow still, cause there is the need to wake-up the objects for the retrieval of allowed transitions for each item. To solve this shortcoming, we render the list without action buttons bar first (so the list is displayed very fast) and once displayed, we retrieve the allowed transitions for each displayed item with an ajax call. This call returns the actions allowed , but not the translations. So, I guess we can use handlebars to manage both the html to be rendered and the translations. Worth to say that once the user select items, the action buttons bar is rendered at the bottom as expected, but only the actions all selected items have in common are displayed. This solves the confusion that all actions appear available at the bottom, no matter if the transition can be performed to the selected items or not.
