### ISSUE TITLE
ID Server known issues

### ISSUE THREAD

**Issue by mikejmets** [bikalims/bika.lims#2119]
The new ID Server seems to look and work very well but was done on a shoe string budget so is short on a certain things:
* there is no validation of the values/constraints/formats entered
* unit tests could be extended
* documentation and on screen instructions are weak

**Comment by lemoene** [comment]
If you could spend a few minutes on the instructions it'll help already (when you have a gap) thank

**Comment by ramonski** [comment]
Thanks @mikejmets, I appreciate your efforts. It is a central and important piece of code in Bika LIMS and we need to take care that this ID machinery does not behave unexpected.

Please go on with testing and documenting the gaps within this issue, so we have at least a place we can refer.

From my wishlist:

A view to manage the numbers in the number storage would be nice (at least to view the different keys).

Well done Mike, go on like this:)

**Comment by mikejmets** [comment]
Will do @ramonski .  And all contributions are welcome :-) There already is a view of the keys, what do what a way to change them in the UI?

**Comment by ramonski** [comment]
@mikejmets: I merged the your IDServer upgrade step to `to340.py`, as this will be the targeted version to include this feature. However, I've seen that the prepared `config_map` is nowhere applied: https://github.com/bikalabs/bika.lims/blob/master/bika/lims/upgrade/to340.py#L33

Is this by purpose?

**Comment by mikejmets** [comment]
Well spotted @ramonski. I provided a default for a IDFormattingField for new sites and a config_map that could be customised for upgrading existing sites. So yes, this should be written in flashing lights: before upgrading an existing site ensure that the existing ID server customizations are reflecting in the upgrade config map. Please let me know if you have any good ideas on how to improve on this.
