### ISSUE TITLE
 New AR Add Form: Don't offer primary selected Contact again for CC Contacts

### ISSUE THREAD

**Issue by lemoene** [bikalims/bika.lims#2160]
## Steps to reproduce

Create new AR inside Batch for client Klaymore. The Contact is correctly auto filled with Johanna Smith as she is the only one at the Client. Regardless, the primary selected Contact should not be offered as CC Contact again on the field below

## Current behavior

Johanna Smith is offered again as CC Contact

## Expected behavior

A look-up with all the Client's other Contacts

**Comment by lemoene** [comment]
This one I think was in the old form too

**Comment by lemoene** [comment]
More problems with the Github tracker, edit of title and comments don't work? Neither styling both FF and Chromium

TITLE should be: AR Create. Please don't offer primary selected Contact again for CC Contacts

**Comment by ramonski** [comment]
Fields in GitHub work all fine for me (Chrome on OSX)

**Comment by lemoene** [comment]
All broken for me, ff and chromium on Ubuntu, painful. I am out of time for today, but if I cannot fix it i'll have to continue in Jira (with Jira Capture, an absolute pleasure)

Also lets not use Slack threads anymore, missed your message (again)

**Comment by ramonski** [comment]
I think we should not omit this possibility, as it might make sense for testing purpose – Closing this issue.
