### ISSUE TITLE
Analyses sections cannot be expanded in New Analysis Request form using Google Chrome browser

### ISSUE THREAD

**Issue by cpang2** [bikalims/bika.lims#2172]
## Steps to reproduce
1. Select a client and click on the button to create analysis request
2. Click on "Field Analyses" or "Lab Analyses" text labels

## Current behavior
Nothing happens

## Expected behavior
The section should be expanded listing all analysis services. It works on Internet Explorer and Firefox browsers.

## Screenshot (optional)
![chrome](https://user-images.githubusercontent.com/28729494/29161995-6b452056-7db8-11e7-814c-7f89004ba9f9.PNG)
![ie](https://user-images.githubusercontent.com/28729494/29161994-6b43727e-7db8-11e7-8be7-a31afe5a9bdb.PNG)

**Comment by ramonski** [comment]
Does it work for you on https://bikalims.ridingbytes.com?
Have you tried to flush your Chrome Browser Cache or holding the Shift-Key and clicking the reload button?

Von meinem iPhone gesendet

**Comment by lemoene** [comment]
Also see https://jira.bikalabs.com/browse/BC-111

**Comment by cpang2** [comment]
Hi Ramon, flushing the cache did the trick. Thanks!
