### ISSUE TITLE
Bika doesn't install with plone version 5.0.7

### ISSUE THREAD

**Issue by ColinAnthony** [bikalims/bika.lims#2182]
## Steps to reproduce
Ubuntu 16.04
fresh install of plone 5.0.7
follow instillation steps on bika lims github repo
run 
`sudo -u plone_buildout bin/buildout`
## Current behavior

`Error: The requirement ('Plone<=4.3.11') is not allowed by your [versions] constraint (5.0.7)`
## Expected behavior
*************** PICKED VERSIONS ****************
[versions]
Babel = 1.3
...
plone.jsonapi.core = 0.4
*************** /PICKED VERSIONS ***************

**Comment by ramonski** [comment]
Bika LIMS >= 3.2.1b3 is at the moment only compatible with Plone 4.3.x (4.3.15 at the time of writing).

Bika LIMS < 3.2.1b3 is only compatible with Plone 4.3.11.

Please pin Plone in your buildout to this version.
