### ISSUE TITLE
Analyses with Calculated results, do not proceed beyond Received state

### ISSUE THREAD

**Issue by lemoene** [bikalims/bika.lims#2196]
More screenshots and possibly related behaviour at  https://jira.bikalabs.com/browse/BC-134

## Steps to reproduce

Create AR with Calculated results, see https://bikalims.ridingbytes.com/clients/client-2/H2O17-0060-R1 with Total Hardness = Mg + Ca

and capture  its results.

## Current behavior

On submitting the dependent results Mg & Ca, the Hardness is calculated correctly.  Submitting the results advances the AR to _To be Verified_ but not the individual Analyses, neither Calculated or Dependent.

The AR was also advanced to _Verified_ after Verifying the Analyses

![image](https://user-images.githubusercontent.com/1196034/29837670-1748ba76-8cf9-11e7-9dd1-cbc526027a46.png)

![image](https://user-images.githubusercontent.com/1196034/29837912-dca585e2-8cf9-11e7-8d45-927e21946ddc.png)

## Expected behavior

Upon submitting the Analyses, they should advance to state _To be Verified_, and after Verification, to _Verified_

**Comment by ramonski** [comment]
@mikejmets: Was this the issue we fixed recently?

**Comment by mikejmets** [comment]
Yes, I think so.
