### ISSUE TITLE
Worksheet "Show More" Button in Listing View breaks the whole Layout

### ISSUE THREAD

**Issue by ramonski** [bikalims/bika.lims#2225]
## Steps to reproduce

Create a new Worksheet and search for a customer.
Click on the "Show more" Button in the lower right corner of the Table (maybe two times)

## Current behavior

The layout breaks and the calendar is shown on the bottom of the Table.
No further Analyses are shown.

## Expected behavior

"Show more" Button works as expected

## Screenshot (optional)

<img width="1351" alt="ws17-015_ _bika" src="https://user-images.githubusercontent.com/713193/30415957-9e88dbd2-992a-11e7-8cfc-3ced6c83ce9a.png">

**Comment by ramonski** [comment]
The problem is located here:
https://github.com/bikalims/bika.lims/blob/master/bika/lims/browser/js/coffee/bika.lims.bikalisting.coffee#L42

The `data` variable holds the entire site HTML instead of just the table.
The URL for the Ajax request is calculated here:
https://github.com/bikalims/bika.lims/blob/master/bika/lims/browser/bika_listing.py#L736

**Comment by sibghatMCS** [comment]
Same issue occurred in Analysis Profile.
