### ISSUE TITLE
Analysis Specification are not saved

### ISSUE THREAD

**Issue by Ubaid-UrRehman** [bikalims/bika.lims#2261]
Hi,
I have a Bika lims installation on linux machine of version 3.1.6(bika). When I am going to define Analysis Specifications for any sample type and click save button, the values are not saved and it give an error.
Following is the log:
2017-10-05 10:10:43 ERROR Zope.SiteErrorLog 1507180243.580.573759988964 http://localhost:8080/Plone/bika_setup/bika_analysisspecs/analysisspec-8/log
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.bika_listing, line 560, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
  Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/ubaid/Plone/zinstance/src/bika.lims/bika/lims/browser/templates/log.pt
   - Line 26, Column 2
   - Expression: <PathExpr standard:u'view/contents_table'>
   - Names:
      {'args': (),
       'container': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'context': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'default': <object object at 0x7f1c6ca8d4f0>,
       'here': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f1c545f5998>,
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/bika_setup/bika_analysisspecs/analysisspec-8/log>,
       'root': <Application at >,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f1c587a0dd0>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>,
       'view': <Products.Five.metaclass.LogView object at 0x7f1c545837d0>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f1c5453c210>}
  Module zope.tales.expressions, line 217, in __call__
  Module Products.PageTemplates.Expressions, line 155, in _eval
  Module Products.PageTemplates.Expressions, line 117, in render
  Module bika.lims.browser.bika_listing, line 787, in contents_table
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 522, in do_optTag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 522, in do_optTag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 852, in do_condition
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 405, in do_startTag
  Module zope.tal.talinterpreter, line 482, in attrAction_tal
  Module Products.PageTemplates.Expressions, line 225, in evaluateText
  Module zope.tales.tales, line 696, in evaluate
   - URL: /home/ubaid/Plone/zinstance/src/bika.lims/bika/lims/browser/templates/bika_listing_table.pt
   - Line 564, Column 16
   - Expression: <PythonExpr (item[column])>
   - Names:
      {'args': (<Products.Five.metaclass.LogView object at 0x7f1c545837d0>,),
       'container': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'context': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'default': <object object at 0x7f1c6ca8d4f0>,
       'here': <AnalysisSpec at /Plone/bika_setup/bika_analysisspecs/analysisspec-8>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f1c545f5b50>,
       'request': <HTTPRequest, URL=http://localhost:8080/Plone/bika_setup/bika_analysisspecs/analysisspec-8/log>,
       'root': <Application at >,
       'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7f1c587aabd0>,
       'traverse_subpath': [],
       'user': <PropertiedUser 'admin'>,
       'view': <bika.lims.browser.bika_listing.BikaListingTable object at 0x7f1c544a7810>,
       'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7f1c544a7fd0>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (item[column])
  Module <string>, line 1, in <module>
KeyError: u'rangecomment'

**Comment by ramonski** [comment]
Hi @Ubaid-UrRehman thanks for reporting. Please update to the latest Bika LIMS Version at https://pypi.python.org/pypi/bika.lims and re-test again. Thanks
