### ISSUE TITLE
Upgrade to 3.2.1rc3 --> dependencies not downloaded automatically

### ISSUE THREAD

**Issue by holoxy** [bikalims/bika.lims#2285]
I´ve tried to update from bika 3.1.5 to 3.2.1rc3, but none of the following worked:

1. Running bin/buildout -n

2. Adding 3.2.1rc3 in the "version" section of buildout.cfg

3. Adding 3.2.1b3 in the "version" section of buildout.cfg

4. Adding bika.lims>=3.2 in the "eggs" section

5. Following this instruction:

https://sourceforge.net/p/bika/mailman/message/36060938/

--> No version 3.2.x showing up in the "show old upgrades" section

Therefore I downloaded 3.2.1rc3 from pypi manually, put it in the dist folder and did a buildout afterwards.

Unfortunately the depending modules were not downloaded automatically, like

- CairoSVG
- Pyphen
- tinycss
- zope-app.content
- Werkzeug
- pycparser
- plone.app.jquery
- magnitude
- z3c.unconfigure
- z3c.jbot
- WeasyPring
- Products.TinyMCE

Downloading the missing dependencies worked and buildout was possible afterwards

System:
OpenSuse Leap 42.3, Phython 2.7

**Comment by ramonski** [comment]
Probably a local computer issue (maybe you have a proxy configured?). Please download the missing packages from https://pypi.python.org into your local buildout cache

**Comment by holoxy** [comment]
I´m not using a proxy and for 3.15 everything worked perfectly.
My understanding of the RC is, that everything should work just like a stable release. Therefore I reported, that the automatic download does not work.
Manual downloading and putting the files in the buildout folder works, but shouldn´t be standard procedure from my point of view.

**Comment by holoxy** [comment]
I´m not using a proxy and for 3.15 everything worked perfectly.
My understanding of the RC is, that everything should work just like a stable release. Therefore I reported, that the automatic download does not work.
Manual downloading and putting the files in the buildout folder works, but shouldn´t be standard procedure from my point of view.
