### ISSUE TITLE
3.2.1rc3 --> ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by holoxy** [bikalims/bika.lims#2286]
After upgrading from 3.1.5 to 3.2.1rc3 the bika server and clients are no longer reachable.

Chromium error message: 
- ERR_CONNECTION_REFUSED (for client1 and Client2, ports 8080 and 8081)
- ERR_INVALID_HTTP_RESPONSE (for zeoserver, port 8100)

For bika.lims 3.1.5 everything works fine.

Upgrading was done by manual download of the 3.2.1rc3 version from pypi to the dist folder and manual download of the missing dependencies, like

    CairoSVG
    Pyphen
    tinycss
    zope-app.content
    Werkzeug
    pycparser
    plone.app.jquery
    magnitude
    z3c.unconfigure
    z3c.jbot
    WeasyPring
    Products.TinyMCE

to the dist folder also.

Output during the buildout -n:

Uninstalling unifiedinstaller. 
Uninstalling zopepy. 
Uninstalling backup. 
Uninstalling client2. 
Uninstalling client1. 
Uninstalling zeoserver. 
Installing zeoserver. 
Created directory /home/dummy/Plone/zeocluster/parts/zeoserver 
Created directory /home/dummy/Plone/zeocluster/parts/zeoserver/etc 
Created directory /home/dummy/Plone/zeocluster/parts/zeoserver/var 
Created directory /home/dummy/Plone/zeocluster/parts/zeoserver/log 
Created directory /home/dummy/Plone/zeocluster/parts/zeoserver/bin 
Wrote file /home/dummy/Plone/zeocluster/parts/zeoserver/etc/zeo.conf 
Wrote file /home/dummy/Plone/zeocluster/parts/zeoserver/bin/zeoctl 
Changed mode for /home/dummy/Plone/zeocluster/parts/zeoserver/bin/zeoctl to 755 
Wrote file /home/dummy/Plone/zeocluster/parts/zeoserver/bin/runzeo 
Changed mode for /home/dummy/Plone/zeocluster/parts/zeoserver/bin/runzeo to 755 
Installing client1. 
/home/dummy/Plone/zeocluster/lib/python2.7/site-packages/pkg_resources/__init__.py:193: RuntimeWarning: You have iterated over the result of pkg_resources
.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a t
uple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug
with the setuptools project describing that need. 
 stacklevel=1, 
Getting distribution for 'plone.app.jquery>1.6'. 
warning: no previously-included files matching '*.pyc' found anywhere in distribution 
warning: no previously-included files matching '*~' found anywhere in distribution 
Got plone.app.jquery 1.11.2. 
Generated script '/home/dummy/Plone/zeocluster/bin/client1'. 
Generated interpreter '/home/dummy/Plone/zeocluster/parts/client1/bin/interpreter'. 
Generated script '/home/dummy/Plone/zeocluster/bin/createfontdatachunk.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/enhancer.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/explode.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/gifmaker.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/painter.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/pilconvert.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/pildriver.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/pilfile.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/pilfont.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/pilprint.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/player.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/thresholder.py'. 
Generated script '/home/dummy/Plone/zeocluster/bin/viewer.py'. 
Installing client2. 
Generated script '/home/dummy/Plone/zeocluster/bin/client2'. 
Generated interpreter '/home/dummy/Plone/zeocluster/parts/client2/bin/interpreter'. 
Installing backup. 
Generated script '/home/dummy/Plone/zeocluster/bin/backup'. 
Generated script '/home/dummy/Plone/zeocluster/bin/fullbackup'. 
Generated script '/home/dummy/Plone/zeocluster/bin/snapshotbackup'. 
Generated script '/home/dummy/Plone/zeocluster/bin/restore'. 
Generated script '/home/dummy/Plone/zeocluster/bin/snapshotrestore'. 
Installing zopepy. 
Generated interpreter '/home/dummy/Plone/zeocluster/bin/zopepy'. 
Installing unifiedinstaller. 
Versions had to be automatically picked. 
The following part definition lists the versions picked: 
[versions] 
Products.ATExtensions = 1.1a3 
Werkzeug = 0.7.2 
bika.lims = 3.2.1rc3 
cairocffi = 0.8.0 
cffi = 1.11.2 
plone.app.jquery = 1.11.2 

# Required by: 
# bika.lims==3.2.1rc3 
Products.AdvancedQuery = 3.0.4 

# Required by: 
# bika.lims==3.2.1rc3 
Products.DataGridField = 1.9.6 

# Required by: 
# WeasyPrint==0.19.2 
Pyphen = 0.9.4 

# Required by: 
# bika.lims==3.2.1rc3 
collective.progressbar = 0.5 

# Required by: 
# bika.lims==3.2.1rc3 
gpw = 0.2 

# Required by: 
# bika.lims==3.2.1rc3 
magnitude = 0.9.4 

# Required by: 
# bika.lims==3.2.1rc3 
plone.jsonapi.core = 0.5 

# Required by: 
# cffi==1.11.2 
pycparser = 2.18 

# Required by: 
# bika.lims==3.2.1rc3 
z3c.jbot = 0.7.2

------------------------------------------------------

System:
OpenSuse Leap 42.3, Python 2.7, Chromium and/or Firefox

**Comment by ramonski** [comment]
Is your ZEO Server running on 8100? Please also paste the console output here when you startup one of your instances in foreground, e.g. `bin/instance fg`
