### ISSUE TITLE
Better ID server setup text

### ISSUE THREAD

**Issue by lemoene** [bikalims/bika.lims#2287]
## Steps to reproduce

Navigate to ID server setup, /bika_setup/edit

## Current behavior

Poor explanation to the user on how to configure IDs

## Expected behavior

Something better, such as scripted at https://docs.google.com/document/d/1uwb7ocMMTphebqlTBpx2ZAUHa20wiBUIUNdiML1PlxQ/edit

Hopefully the formatting survives, and it is a simple cut and paste

not sure about 

a) the coded Python for the objects
User/Analyst	{user}?
Instrument	{instrument}?
Batch		{batch}?

and b)
What is meant by 
_The number of parts to be included in the prefix_

**Comment by ramonski** [comment]
Included in https://github.com/bikalims/bika.lims/pull/2311
