### ISSUE TITLE
Installation fails with Couldn't find index page for 'bika.lims' (maybe misspelled?)

### ISSUE THREAD

**Issue by denshade** [bikalims/bika.lims#2301]
## Steps to reproduce
   34  wget https://launchpad.net/plone/4.3/4.3.14/+download/Plone-4.3.14-UnifiedInstaller.tgz
   35  tar -xzvf Plone-4.3.14-UnifiedInstaller.tgz
   36  cd Plone-4.3.14-UnifiedInstaller
   38  ./install.sh --target=/usr/local/Plone --build-python zeo
   40  cd /usr/local/Plone/zeocluster
   44  nano buildout.cfg
   45  sudo -u plone_buildout bin/buildout
With 
# Eggs
# ----
# Add an indented line to the eggs section for any Python
# eggs or packages you wish to include in your Plone instance.
#
# Note that versions may be specified here or in the [versions]
# section below. You should always specify versions that you know
# are compatible with the Plone release and at an acceptable
# development level.
#
# If you update to a later version of Plone, remove the hotfix.
#
eggs =
    Plone
    Pillow
    bika.lims

## Current behavior
  sudo -u plone_buildout bin/buildout
Updating zeoserver.
Installing client1.
/usr/local/Plone/buildout-cache/eggs/setuptools-27.3.0-py2.7.egg/pkg_resources/__init__.py:188: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Couldn't find index page for 'bika.lims' (maybe misspelled?)
Getting distribution for 'bika.lims'.
Couldn't find index page for 'bika.lims' (maybe misspelled?)
While:
  Installing client1.
  Getting distribution for 'bika.lims'.
Error: Couldn't find a distribution for 'bika.lims'.

## Expected behavior
Successful installation.

**Comment by ramonski** [comment]
Please try to add the `-n` flag after `bin/buildout` or specify `prefer-final=false`

**Comment by denshade** [comment]
I've tried  sudo -u plone_buildout bin/buildout -n
This gives the same problem: 
Couldn't find index page for 'plone.recipe.precompiler' (maybe misspelled?)
Couldn't find index page for 'plone.recipe.command' (maybe misspelled?)
Updating zeoserver.
Installing client1.
/usr/local/Plone/buildout-cache/eggs/setuptools-27.3.0-py2.7.egg/pkg_resources/__init__.py:188: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Couldn't find index page for 'bika.lims' (maybe misspelled?)
Getting distribution for 'bika.lims'.
Couldn't find index page for 'bika.lims' (maybe misspelled?)
While:
  Installing client1.
  Getting distribution for 'bika.lims'.
Error: Couldn't find a distribution for 'bika.lims'.

**Comment by ramonski** [comment]
Probably a local issue on your computer. Please download the latest distro package from https://pypi.python.org/pypi/bika.lims/ into your buildout cache folder.
