### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by tamanna-vohra** [bikalims/bika.lims#2324]
## Current behavior
life threat alerts is nowhere to be found
## Expected behavior
it should be easier to find. Software is to difficult to navigate

**Comment by lemoene** [comment]
Which version are you using?

If you find it too difficult, you van always ask your money back.

**Comment by tamanna-vohra** [comment]
Plone 4.3.11 (4314)
CMF 2.2.9
Zope 2.13.24
Python 2.7.12 (default, Nov 22 2017, 06:13:16) [GCC 4.8.4]
PIL 3.3.1 (Pillow)

These are the specifications

**Comment by lemoene** [comment]
Which Bika?

**Comment by tamanna-vohra** [comment]
Bika Health

**Comment by lemoene** [comment]
You don't necessarily have a bug, but need user support. This is not the place for it. Please post to the Bika Health group for voluntary assistance, https://groups.google.com/forum/?hl=en#%21forum/bika-health, or contact a professional service provider, see https://www.bikalims.org/support-and-service-provision#proproviders.

For the former, you are going to get nowhere asking poorly explained or researched questions and expecting to be spoonfed
